"""Generate safe native RPC adapters from the checked-in SolarXR schema.

No separate network protocol: generated code calls the upstream Rust bindings.
Run from any directory; the resulting Rust source is checked in.
"""
import re, json
from pathlib import Path
root = Path(__file__).resolve().parents[2]
entities = {}
scalar = {'bool':'bool','byte':'i8','int8':'i8','ubyte':'u8','uint8':'u8','short':'i16','int16':'i16','ushort':'u16','uint16':'u16','int':'i32','int32':'i32','uint':'u32','uint32':'u32','long':'i64','int64':'i64','ulong':'u64','uint64':'u64','float':'f32','float32':'f32','double':'f64','float64':'f64'}
for file in sorted((root/'solarxr-protocol/schema').rglob('*.fbs')):
    text=re.sub(r'//[^\n]*','',file.read_text())
    ns=re.search(r'namespace\s+([\w.]+)',text).group(1)
    for match in re.finditer(r'(table|struct|enum|union)\s+(\w+)\s*(?::\s*(\w+))?\s*(?:\([^)]*\))?\s*\{([^}]+|)\}',text,re.S):
        kind,name,base,body=match.groups()
        item={'ns':ns,'name':name,'kind':kind,'base':base or 'uint8','fields':[],'variants':[]}
        if kind in ('table','struct'):
            for field in body.split(';'):
                if 'deprecated' in field or not field.strip():continue
                f=re.match(r'\s*(\w+)\s*:\s*(\[?[\w.]+\]?)\s*(?:=\s*([^()]+?))?\s*(?:\([^)]*\))?\s*$',field)
                if not f:raise ValueError((name,field))
                key,typ,default=f.groups();item['fields'].append((key,typ,default.strip() if default else None))
        else:
            value=0
            for part in body.split(','):
                part=re.sub(r'\([^)]*\)','',part).strip()
                if not part:continue
                m=re.match(r'([\w.]+)(?:\s*=\s*(\d+))?$',part)
                if not m:raise ValueError((name,part))
                label,explicit=m.groups()
                if explicit:value=int(explicit)
                item['variants'].append((label,value));value+=1
        entities[ns+'.'+name]=item

def resolve(typ,ns):
    if typ in scalar or typ=='string':return typ
    if typ in entities:return typ
    if ns+'.'+typ in entities:return ns+'.'+typ
    raise ValueError((typ,ns))
def rp(typ):return 'sx::'+typ.removeprefix('solarxr_protocol.').replace('.', '::')
def ident(typ):return typ.removeprefix('solarxr_protocol.').replace('.', '_')
def method(field):return field+'_' if field in ('type','loop','match','ref','move','mod','self') else field

def valexpr(v,typ,ns):
    typ=resolve(typ,ns)
    if typ in scalar:
        rust=scalar[typ]
        if rust=='bool':return f'boolean({v})?'
        if rust=='f32':return f'float32({v})?'
        if rust=='f64':return f'number({v})?'
        return f'{rust}::try_from({"signed" if rust.startswith("i") else "unsigned"}({v})?).map_err(|_| "Number is outside its allowed range".to_string())?'
    e=entities[typ]
    if e['kind']=='enum':return f'{rp(typ)}(enum_value({v}, ENUM_{ident(typ)})? as {scalar[e["base"]]})'
    if e['kind']=='struct':return f'struct_{ident(typ)}({v})?'
    raise ValueError(('scalar expression',typ))

def decode_expr(expr,typ,ns):
    typ=resolve(typ,ns)
    if typ in scalar:return f'json!({expr})'
    if typ=='string':return f'json!({expr})'
    e=entities[typ]
    if e['kind']=='enum':return f'json!({expr}.0)'
    return f'decode_{ident(typ)}({"&" if e["kind"]=="struct" else ""}{expr})'

out=['// @generated by scripts/generate-rpc.py; maintain through the generator.', '#![allow(non_snake_case, non_upper_case_globals, unused_variables, unused_mut, dead_code, clippy::needless_borrow, clippy::redundant_closure, clippy::redundant_field_names, clippy::useless_conversion)]', 'use solarxr_protocol::{self as sx, flatbuffers as fb};','use serde_json::{Value, json};', '''fn boolean(v: &Value) -> Result<bool,String> { v.as_bool().ok_or_else(|| "Expected a switch value".into()) }
fn signed(v:&Value)->Result<i64,String>{v.as_i64().ok_or_else(||"Expected a whole number".into())}
fn unsigned(v:&Value)->Result<u64,String>{v.as_u64().ok_or_else(||"Expected a nonnegative whole number".into())}
fn number(v:&Value)->Result<f64,String>{v.as_f64().filter(|v|v.is_finite()).ok_or_else(||"Expected a finite number".into())}
fn float32(v:&Value)->Result<f32,String>{let n=number(v)?;if n.abs()>f32::MAX as f64{return Err("Number is outside its allowed range".into());}Ok(n as f32)}
fn enum_value(v:&Value, values:&[(&str,u64)])->Result<u64,String>{ if let Some(name)=v.as_str(){values.iter().find(|(n,_)|*n==name).map(|(_,v)|*v)}else{v.as_u64().filter(|v|values.iter().any(|(_,n)|*n==*v))}.ok_or_else(||"Unknown selection".into()) }
''']
# Only types reachable from RPC or pub/sub envelopes are generated.
needed=set()
def visit(typ):
    if typ in needed or typ not in entities:return
    needed.add(typ);e=entities[typ]
    for _,ft,_ in e['fields']:visit(resolve(ft.strip('[]'),e['ns']))
    if e['kind']=='union':
        for variant,_ in e['variants']:visit(resolve(variant,e['ns']))
visit('solarxr_protocol.rpc.RpcMessageHeader');visit('solarxr_protocol.pub_sub.PubSubHeader')
for typ in sorted(needed):
    e=entities[typ];n=ident(typ);t=rp(typ);fields=e['fields']
    if e['kind']=='enum':
        out.append(f'pub static ENUM_{n}: &[(&str,u64)] = &{json.dumps(e["variants"]).replace("[", "[").replace("]", "]")};'.replace('["','("').replace('", ', '", ').replace('],', '),').replace(']];', ')];'))
        # Emit Rust tuple literals for tuple-valued defaults.
        out[-1]=f'pub static ENUM_{n}: &[(&str,u64)] = &[ '+', '.join(f'("{v}",{x})' for v,x in e['variants'])+' ];'
        continue
    if e['kind']=='union':
        out.append(f'fn encode_{n}<\'a>(f:&mut fb::FlatBufferBuilder<\'a>,v:&Value)->Result<({t},fb::WIPOffset<fb::UnionWIPOffset>),String>{{match v["type"].as_str().unwrap_or("") {{')
        for variant,_ in e['variants']:
            dest=resolve(variant,e['ns']);label=variant.split('.')[-1]
            out.append(f'"{label}"=>Ok(({t}::{variant.replace('.', '_')},encode_{ident(dest)}(f,&v["value"])?.as_union_value())),')
        out.append('_=>Err("Unknown operation type".into())}}')
        continue
    lt="<'_>" if e['kind']=='table' else ''
    out.append(f'fn decode_{n}(v:{"&" if e["kind"]=="struct" else ""}{t}{lt})->Value{{let mut o=serde_json::Map::new();')
    for key,ft,default in fields:
        if e['name']=='SaveFileNotification' and key=='data':
            out.append('o.insert("data_size".into(),json!(v.data().map(|a|a.len()).unwrap_or(0)));');continue
        expr=f'v.{method(key)}()';vector=ft.startswith('[');rt=resolve(ft.strip('[]'),e['ns']);ek=entities.get(rt,{}).get('kind')
        if ek=='union':
            out.append(f'let value=match v.{key}_type() {{')
            for variant,_ in entities[rt]['variants']:
                dest=resolve(variant,e['ns']);label=variant.split('.')[-1]
                snake=re.sub(r'(?<!^)(?=[A-Z])','_',label).lower()
                # Names from bindings preserve acronyms as snake words (OTA => ota).
                generated=list((root/'solarxr-protocol/protocol/rust/src/generated').rglob('*_generated.rs'))
                source=next(p for p in generated if f'pub struct {e["name"]}<' in p.read_text()).read_text()
                getters=re.findall(r'pub fn (\w+)\(\s*&self\s*,?\s*\)\s*->\s*Option<([\s\S]*?)>\s*\{',source)
                getter=next((g for g,r in getters if label in r and g.startswith(key+'_as_')),None)
                if getter is None:
                    getter=next((g for g,r in getters if label in r and g.startswith(key+'_as_')), None)
                if getter is None: raise ValueError((e['name'], key, label, getters))
                out.append(f'{rp(rt)}::{variant.replace('.', '_')}=>v.{getter}().map(|x|json!({{"type":"{label}","value":decode_{ident(dest)}(x)}})).unwrap_or(Value::Null),')
            out.append('_=>Value::Null};');value='value'
        elif vector:
            inner=decode_expr('x',rt,e['ns']);value=f'{expr}.map(|a|Value::Array(a.iter().map(|x|{inner}).collect())).unwrap_or(Value::Null)'
        elif rt=='string' or ek=='table' or (e['kind']=='table' and ek=='struct') or default=='null':
            inner=decode_expr('x',rt,e['ns']);value=f'{expr}.map(|x|{inner}).unwrap_or(Value::Null)'
        else:value=decode_expr(expr,rt,e['ns'])
        out.append(f'o.insert("{key}".into(),{value});')
    out.append('Value::Object(o)}')
    if e['kind']=='struct':
        args=','.join(valexpr(f'&v["{key}"]',ft,e['ns']) for key,ft,_ in fields)
        out.append(f'fn struct_{n}(v:&Value)->Result<{t},String>{{Ok({t}::new({args}))}}')
        continue
    out.append(f'fn encode_{n}<\'a>(f:&mut fb::FlatBufferBuilder<\'a>,v:&Value)->Result<fb::WIPOffset<{t}<\'a>>,String>{{')
    out.append('if !v.is_object(){return Err("Expected an object".into());}')
    assigned=[]
    for key,ft,default in fields:
        rt=resolve(ft.strip('[]'),e['ns']);ek=entities.get(rt,{}).get('kind');value=f'&v["{key}"]';m=method(key)
        if ek=='union':
            out.append(f'let {m}=if v["{key}"].is_null(){{None}}else{{Some(encode_{ident(rt)}(f,{value})?)}};')
            assigned += [f'{key}_type:{m}.as_ref().map(|x|x.0).unwrap_or({rp(rt)}::NONE)',f'{m}:{m}.map(|x|x.1)'];continue
        if ft.startswith('['):
            if rt=='string':inner='f.create_string(x.as_str().ok_or("Expected text")?)'
            elif ek=='table':inner=f'encode_{ident(rt)}(f,x)?'
            else:inner=valexpr('x',rt,e['ns'])
            out.append(f'if !v["{key}"].is_null()&&!v["{key}"].is_array(){{return Err("Expected an array".into());}}')
            out.append(f'let {m}=if let Some(a)=v["{key}"].as_array(){{let mut offsets=Vec::new();for x in a{{offsets.push({inner});}}Some(f.create_vector(&offsets))}}else{{None}};')
            assigned.append(f'{m}:{m}');continue
        if rt=='string':out.append(f'if !v["{key}"].is_null()&&!v["{key}"].is_string(){{return Err("Expected text".into());}}');out.append(f'let {m}=v["{key}"].as_str().map(|s|f.create_string(s));');assigned.append(f'{m}:{m}');continue
        if ek=='table':out.append(f'let {m}=if v["{key}"].is_null(){{None}}else{{Some(encode_{ident(rt)}(f,{value})?)}};');assigned.append(f'{m}:{m}');continue
        if ek=='struct':out.append(f'let {m}=if v["{key}"].is_null(){{None}}else{{Some(struct_{ident(rt)}({value})?)}};');assigned.append(f'{m}:{m}.as_ref()');continue
        inner=valexpr(value,rt,e['ns'])
        if default=='null':assigned.append(f'{m}:if v["{key}"].is_null(){{None}}else{{Some({inner})}}')
        else:assigned.append(f'{m}:if v["{key}"].is_null(){{{t}Args::default().{m}}}else{{{inner}}}')
    out.append(f'Ok({t}::create(f,&{t}Args{{'+','.join(assigned)+'}))}')

rpc=entities['solarxr_protocol.rpc.RpcMessage']['variants']
out.append('pub static RPC_NAMES: &[&str]= &['+','.join(json.dumps(n) for n,_ in rpc)+'];')
out.append('pub fn encode_rpc(name:&str,value:&Value,tx:u32)->Result<Vec<u8>,String>{let mut f=fb::FlatBufferBuilder::new();let(kind,body)=encode_rpc_RpcMessage(&mut f,&json!({"type":name,"value":value}))?;let tx=sx::datatypes::TransactionId::new(tx);let header=sx::rpc::RpcMessageHeader::create(&mut f,&sx::rpc::RpcMessageHeaderArgs{tx_id:Some(&tx),message_type:kind,message:Some(body)});let headers=f.create_vector(&[header]);let bundle=sx::MessageBundle::create(&mut f,&sx::MessageBundleArgs{rpc_msgs:Some(headers),..Default::default()});f.finish(bundle,None);Ok(f.finished_data().to_vec())}')
out.append('pub fn encode_rpc_batch(requests:&[(String,Value)],tx:u32)->Result<Vec<u8>,String>{if requests.len()>128{return Err("Too many operations".into());}let mut f=fb::FlatBufferBuilder::new();let mut headers=Vec::new();for(name,value)in requests{let(kind,body)=encode_rpc_RpcMessage(&mut f,&json!({"type":name,"value":value}))?;let id=sx::datatypes::TransactionId::new(tx);headers.push(sx::rpc::RpcMessageHeader::create(&mut f,&sx::rpc::RpcMessageHeaderArgs{tx_id:Some(&id),message_type:kind,message:Some(body)}));}let headers=f.create_vector(&headers);let bundle=sx::MessageBundle::create(&mut f,&sx::MessageBundleArgs{rpc_msgs:Some(headers),..Default::default()});f.finish(bundle,None);Ok(f.finished_data().to_vec())}')
out.append('pub fn decode_rpc(bytes:&[u8])->Result<Vec<(String,u32,Value)>,String>{let bundle=fb::root::<sx::MessageBundle>(bytes).map_err(|e|e.to_string())?;decode_rpc_verified(bundle)}\npub fn decode_rpc_verified(bundle:sx::MessageBundle)->Result<Vec<(String,u32,Value)>,String>{let mut out=Vec::new();if let Some(headers)=bundle.rpc_msgs(){for header in headers{let v=decode_rpc_RpcMessageHeader(header);if let Some(name)=v["message"]["type"].as_str(){out.push((name.to_owned(),header.tx_id().map(|t|t.id()).unwrap_or(0),v["message"]["value"].clone()));}}}Ok(out)}')
out.append('pub fn encode_pubsub(value:&Value)->Result<Vec<u8>,String>{let mut f=fb::FlatBufferBuilder::new();let h=encode_pub_sub_PubSubHeader(&mut f,value)?;let headers=f.create_vector(&[h]);let bundle=sx::MessageBundle::create(&mut f,&sx::MessageBundleArgs{pub_sub_msgs:Some(headers),..Default::default()});f.finish(bundle,None);Ok(f.finished_data().to_vec())}')
out.append('pub fn decode_pubsub(bytes:&[u8])->Result<Vec<Value>,String>{let bundle=fb::root::<sx::MessageBundle>(bytes).map_err(|e|e.to_string())?;decode_pubsub_verified(bundle)}\npub fn decode_pubsub_verified(bundle:sx::MessageBundle)->Result<Vec<Value>,String>{Ok(bundle.pub_sub_msgs().map(|h|h.iter().map(decode_pub_sub_PubSubHeader).collect()).unwrap_or_default())}')
# Describe settings as native controls with labels and field metadata.
out.append('pub fn enum_choices(name:&str)-> &\'static [(&\'static str,u64)]{match name{')
for typ in sorted(needed):
    if entities[typ]['kind']=='enum':out.append(f'"{typ.split(".")[-1]}"=>ENUM_{ident(typ)},')
out.append('_=>&[]}}')
metadata={}
for typ in sorted(needed):
 e=entities[typ]
 if e['kind'] in ('table','struct'):metadata[e['name']]=[{"name":k,"type":resolve(t.strip('[]'),e['ns']).split('.')[-1],"optional":d=='null',"vector":t.startswith('[')} for k,t,d in e['fields']]
out.append('pub fn schema()->Value{serde_json::from_str(r###"'+json.dumps(metadata,separators=(',',':'))+'"###).expect("Generated schema is valid")}')
(root/'gui-gpui/src/rpc_generated.rs').write_text('\n'.join(out)+'\n')
print('Generated',len(needed),'SolarXR types;',len(rpc),'RPC messages')
